version: "2"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/lib/docker/volumes/files/photoalbum.com/certs:/etc/nginx/certs:ro
      - /var/lib/docker/volumes/files/photoalbum.com/htpasswd:/etc/nginx/htpasswd
      - /var/lib/docker/volumes/files/photoalbum.com/nginx_confd/:/etc/nginx/conf.d
      - /var/lib/docker/volumes/files/photoalbum.com/nginx_vhostd/:/etc/nginx/vhost.d
      - /var/lib/docker/volumes/files/photoalbum.com/nginx_html/:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt-nginx:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx
    privileged: true
    volumes:
      - /var/lib/docker/volumes/files/photoalbum.com/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    restart: always

networks:
  default:
    external:
      name: shared

volumes:
        mysql_data:
                driver: local
        nginx_confd:
                driver_opts:
                        type: none
                        device: /var/lib/docker/volumes/files/photoalbum.com/nginx_confd/
                        o: bind
        nginx_vhostd:
                driver_opts:
                        type: none
                        device: /var/lib/docker/volumes/files/photoalbum.com/nginx_vhostd/
                        o: bind
        nginx_html:
                driver_opts:
                        type: none
                        device: /var/lib/docker/volumes/files/photoalbum.com/nginx_httml/
                        o: bind

